import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/feature/layout/Footer";
import { ThemeProvider } from "@/theme/ThemeProvider";
import Header from "@/feature/layout/Header";
import { getAuthSession } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import NoUser from "@/components/NoUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuthSession();
  return (
    <html lang="en" className="h-full">
      <body>
        <div className="flex flex-col h-full">
          <ThemeProvider
          
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            <Header />
            <div className="flex-1 max-w-lg m-auto py-14 w-full">
              {session?(children):(
                
                  <NoUser/>
                
              )}

            </div>
            
          <Footer />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
